spring.application.name=backend

# 기본 실행 프로필
spring.profiles.active=dev

# 1. ?? ???(Multipart) ?? ?? ??
spring.servlet.multipart.enabled=true
spring.servlet.multipart.max-file-size=10MB
spring.servlet.multipart.max-request-size=20MB

# 2. AWS S3 ?? ?? (???? ??)
spring.cloud.aws.credentials.access-key=${AWS_ACCESS_KEY_ID}
spring.cloud.aws.credentials.secret-key=${AWS_SECRET_ACCESS_KEY}
spring.cloud.aws.s3.bucket=${AWS_S3_BUCKET_NAME}
spring.cloud.aws.region.static=ap-northeast-2