spring.application.name=backend

# RDS MySQL 연결 설정
spring.datasource.url=jdbc:mysql://${DB_HOST:localhost}:3306/${DB_NAME:playbit_local_db}?useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true
spring.datasource.username=${DB_USERNAME:root}
spring.datasource.password=${DB_PASSWORD:MySql1234!}
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# JPA 및 Hibernate 설정
spring.jpa.hibernate.ddl-auto=update
spring.jpa.properties.hibernate.format_sql=false
spring.jpa.show-sql=false

# 로그 설정
logging.level.org.hibernate.SQL=debug
logging.level.org.hibernate.orm.jdbc.bind=trace

# 스웨거 설정
springdoc.swagger-ui.enabled=true
springdoc.api-docs.enabled=true

# 알림 관련 설정
webpush.vapid.public-key=BBix2KOIuqxkSBqUapoARSx5vAO-R7xRyiQhkSt3KHGkmoQ8W6i2iuWRaFT29xlKO5LfyMbQdc5l7xIUHYH7SZU
webpush.vapid.private-key=${VAPID_PRIVATE_KEY:dummy-vapid-private-key}
webpush.vapid.subject=mailto:jjuluha11@gmail.com

# 1. 멀티파트 파일 업로드 설정
spring.servlet.multipart.enabled=true
spring.servlet.multipart.max-file-size=10MB
spring.servlet.multipart.max-request-size=20MB

# 2. AWS S3 설정 (보안을 위해 콜론 뒤 더미값 적용)
spring.cloud.aws.credentials.access-key=${AWS_ACCESS_KEY_ID:dummy-access-key}
spring.cloud.aws.credentials.secret-key=${AWS_SECRET_ACCESS_KEY:dummy-secret-key}
spring.cloud.aws.s3.bucket=${AWS_S3_BUCKET_NAME:dummy-bucket}
spring.cloud.aws.region.static=ap-northeast-2

# OSIV를 꺼서 뷰/HTTP 응답 단계까지 DB 커넥션을 끌고 가지 않도록 설정
spring.jpa.open-in-view=false
# 필요 시 커넥션 풀 크기 확장
spring.datasource.hikari.maximum-pool-size=20